name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.6'
    - uses: actions/checkout@v2
    - run: |
        go get -v -t -d ./...
    - run: go test ./...
    - run: go build -ldflags="-s -w" ./cmd/bareos-zabbix-check/
